workflows:
  android-build:
    name: Android build workflow
    max_build_duration: 60 # 1 hour max duration per build (can be increased as needed)
    environment:
      flutter: stable # Optional, if you're using Flutter (remove if you're using pure Android)
      java: corretto11 # JDK version (make sure it matches your Android project)
      gradle: "6.x" # Gradle version
      android: true # Enable Android environment
      cache:
        - ~/.gradle
        - ~/.android
    scripts:
      # Install dependencies
      - name: Install dependencies
        script: |
          echo "Installing dependencies..."
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
          
      # Build APK
      - name: Build APK
        script: |
          echo "Building APK..."
          ./gradlew assembleRelease # Or assembleDebug for Debug APK

    artifacts:
      - app/build/outputs/apk/release/*.apk  # Path to Release APK
      - app/build/outputs/apk/debug/*.apk    # Path to Debug APK (optional)